[world]
name = "Dojo starter"
description = "The official Dojo Starter guide, the quickest and most streamlined way to get your Dojo Autonomous World up and running. This guide will assist you with the initial setup, from cloning the repository to deploying your world."
cover_uri = "file://assets/cover.png"
icon_uri = "file://assets/icon.png"
website = "https://github.com/dojoengine/dojo-starter"
seed = "dojo_starter"

[world.socials]
x = "https://x.com/ohayo_dojo"
discord = "https://discord.gg/FB2wR6uF"
github = "https://github.com/dojoengine/dojo-starter"
telegram = "https://t.me/dojoengine"

[namespace]
default = "dojo_starter"

[env]
rpc_url = "http://localhost:5050/"
# Default account for katana with seed = 0 - UPDATED TO MATCH REAL KATANA
account_address = "0x13d9ee239f33fea4f8785b9e3870ade909e20a9599ae7cd62c1c292b73af1b7"
private_key = "0x1c9053c053edf324aec366a34c6901b1095b07af69495bffec7d7fe21effb1b"

# Additional test accounts for multiple wallet simulation
[test_accounts]
# Katana Account #0 (default) - REAL ACCOUNTS FROM KATANA
player1_address = "0x13d9ee239f33fea4f8785b9e3870ade909e20a9599ae7cd62c1c292b73af1b7"
player1_private_key = "0x1c9053c053edf324aec366a34c6901b1095b07af69495bffec7d7fe21effb1b"

# Katana Account #1 - REAL ACCOUNTS FROM KATANA
player2_address = "0x2af9427c5a277474c079a1283c880ee8a6f0f8fbf73ce969c08d88befec1bba"
player2_private_key = "0x1800000000300000180000000000030000000000003006001800006600"

# Katana Account #2 - REAL ACCOUNTS FROM KATANA
player3_address = "0x5b6b8189bb580f0df1e6d6bec509ff0d6c9be7365d10627e0cf222ec1b47a71"
player3_private_key = "0x33003003001800009900180300d206308b0070db00121318d17b5e6262150b"

# world_address = "0x06171ed98331e849d6084bf2b3e3186a7ddf35574dd68cab4691053ee8ab69d7"

[writers]
"dojo_starter" = ["dojo_starter-battle_actions"]
