[package]
cairo-version = "=2.10.1"
name = "dojo_starter"
version = "1.5.0"
edition = "2024_07"

[cairo]
sierra-replace-ids = true

[scripts]
migrate = "sozo build && sozo migrate"                                                         # scarb run migrate
create_player = "sozo execute dojo_starter-battle_actions create_player --wait"                # scarb run create_player
join_battle = "sozo execute dojo_starter-battle_actions join_battle --wait"                    # scarb run join_battle
attack = "sozo execute dojo_starter-battle_actions perform_action --wait"                      # scarb run attack

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.5.0" }

[[target.starknet-contract]]
build-external-contracts = ["dojo::world::world_contract::world"]

[dev-dependencies]
cairo_test = "=2.10.1"
dojo_cairo_test = { git = "https://github.com/dojoengine/dojo", tag = "v1.5.0" }
